project/news/urls.py
from django.urls import path

# Импортируем созданные нами представления
from .views import PostsList, PostDetails, PostCreate, PostDelete, PostUpdate, subscribe_category, subscribe_author, \
   CommentCreate

urlpatterns = [

   path('', PostsList.as_view(),name="post_list"),
   path('<int:pk>', PostDetails.as_view(), name="post_detail" ),
   path('create/', PostCreate.as_view(), name="post_create"),
   path('news/create/', PostCreate.as_view(), name="news_create"),
   path('<int:pk>/update/', PostUpdate.as_view(), name="post_update"),
   path('news/<int:pk>/update/', PostUpdate.as_view(), name="post_update"),
   path('<int:pk>/delete/', PostDelete.as_view(), name="post_delete"),
   path('news/<int:pk>/update/', PostDelete.as_view(), name="news_delete"),
   path('<int:post_id>/category/<int:category_id>/subscribe', subscribe_category, name='subscribe'),
   path('<int:post_id>/author/<int:author_id>/subscribe', subscribe_author, name='subscribe'),
   path('<int:post_id>/comment', CommentCreate.as_view(), name="comment_add"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('posts/', include('news.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('protect.urls')),
]

project/news/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.urls import reverse

post = "PO"
news = "NE"

STATE = [
    (post, "Post"),
    (news, "News")
]


class Author(models.Model):
    raiting = models.FloatField(default=0)
    user_id = models.OneToOneField(User, on_delete=models.CASCADE, related_name="author_profile")
    subcribes = models.ManyToManyField(User, blank=True, related_name="author")

    def __str__(self):
        return f"{self.user_id.username}"

    def update_raiting(self):
        post_raiting = sum(post.raiting * 3 for post in Post.objects.filter(author=self))
        comments_raiting = sum(comment.comment_raiting for comment in Comment.objects.filter(user_id=self.user_id))
        self.raiting = post_raiting + comments_raiting
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=155)
    subcribes = models.ManyToManyField(User, blank=True, related_name="category")

    def __str__(self):
        return f'{self.name.title()}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    state = models.CharField(max_length=2, choices=STATE, default=post)
    date = models.DateTimeField(auto_now_add=True)
    heading = models.CharField(max_length=155)
    text = models.TextField()
    raiting = models.FloatField(default=0)
    categories = models.ManyToManyField(Category, through="PostCategory")

    def like(self):
        self.raiting += 1
        self.save()

    def dislike(self):
        self.raiting -= 1
        self.save()

    def __str__(self):
        return f" {self.heading} by {self.author.user_id}"

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    comment_raiting = models.FloatField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def like(self):
        self.comment_raiting += 1
        self.save()

    def dislike(self):
        self.comment_raiting -= 1
        self.save()

    def __str__(self):
        return self.text


class InterestingPost(models.Model):
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE)
    post_heading = models.CharField(max_length=155)
    post_date = models.DateTimeField()

    def fill_details_of_post(self):
        self.post_date = self.post_id.date
        self.post_heading = self.post_id.heading


class InterestingPosts(models.Model):
    news = models.ForeignKey(InterestingPost, on_delete=models.CASCADE)

project/templates/add_comment.html
{% extends 'flatpages/default.html' %}


{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ post.heading}}</h1>
<h6>Rating:{{ post.raiting }}</h6>
<h5>Author:<button> <a href="{{post.id}}/author/{{post.author.id}}/subscribe"> Subscribe to author: "{{ post.author.user_id.username }}" </a> </button></h5>
{% if is_author_post %}<button><a href="{{post.id}}/delete"> Delete </a></button>{% endif %}
<h5>Date:{{ post.date|date:'M d Y' }}</h5>

<h6>Categories:
    {% for category in post.categories.all %}
        <button> <a href="{{post.id}}/category/{{category.id}}/subscribe"> Subscribe to a category: "{{ category.name }}"</a> </button>
    {% endfor %}
</h6>

{{ post.text}}
{% if is_comments %}
<h5>Comments:</h5>

{% for comment in comments %}
    <h6>User:{{ comment.user_id }} {{ comment.comment_raiting}}<br>
    {{ comment.text }}<br></h6>


{% endfor %}
{% else %}
       <h6> No comments</h6>
{% endif %}

    <h2>Create Comment</h2>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Post Comment">
    </form>

{% endblock content %}

project/templates/index.html
{% extends "main.html" %}

{% block content %}
<h2>The authorized user's page {{request.user.username}}</h2>
<div> It may contain personal information for each user </div>
{% if is_not_author %}
<button> <a href="upgrade/"> Become an author</a> </button>
{% endif %}
<button> <a href="posts">Watch the posts</a> </button>
<button> <a href="accounts/logout/">Exit</a> </button>
{% endblock %}             

project/templates/mailaut.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Knock-knock...{{ client_name }} Who's there? This is a new post from your favorite author {{ author_name }} </h2>
    <a href="{{ link }}"> {{ heading }} by {{ author }}</a>
    <p></p>
    <p> {{ text|truncatewords:50 }} </p>>
</body>
</html>

project/templates/mailcat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Knock-knock... Who's there? This is a new post in the categories you are interested in {{ category_name }} </h2>
    <a href="{{ link }}"> {{ heading }} by {{ author }}</a>
    <p></p>
    <p> {{ text|truncatewords:50 }} </p>
</body>
</html>

project/templates/mailsched.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weekly News Update</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 20px;
        }

        h2 {
            color: #007BFF;
        }

        a {
            color: #343A40;
            text-decoration: none;
        }

        a:hover {
            text-decoration: underline;
        }

        .post-link {
            margin-bottom: 10px;
            display: block;
        }
    </style>
</head>
<body>
    <h2>The Latest for the Week in Your Favorite Category: {{ category_name }}</h2>
    {% for post in posts %}
        <div class="post-link">
            <a href="http://127.0.0.1:8000/posts/{{post.id}}">
                {{ post.heading }} by {{ post.author }}
            </a>
        </div>
    {% endfor %}
</body>
</html>

project/templates/main.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block head_title %}Simple SignUp/SignIn app{% endblock head_title %}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        header {
            background-color: #333;
            color: white;
            padding: 10px;
            text-align: center;
        }

        header h1 {
            margin: 0;
        }

        nav {
            background-color: #eee;
            padding: 10px;
            text-align: center;
        }

        nav a {
            text-decoration: none;
            color: #333;
            margin: 0 10px;
        }

        nav a:hover {
            color: #555;
        }

        main {
            padding: 20px;
        }

        footer {
            background-color: #333;
            color: white;
            text-align: center;
            padding: 10px;
            position: absolute;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>
    <header>
        <h1><a href="/">Simple SignUp/SignIn app</a></h1>
    </header>

    <nav>
        <!-- Здесь может быть ваше навигационное меню для SignUp/SignIn -->
    </nav>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <!-- Здесь может быть информация о копирайте или другие дополнительные сведения -->
    </footer>
</body>
</html>

project/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}
{% load custom_filters %}

<!-- Название у  нас будет Product -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h1>{{ post.heading|censor}}</h1>
<h6>Rating:{{ post.raiting }}</h6>
<h5>Author:<button> <a href="{{post.id}}/author/{{post.author.id}}/subscribe"> Subscribe to author: "{{ post.author.user_id.username }}" </a> </button></h5>
{% if is_author_post %}<button><a href="{{post.id}}/delete"> Delete </a></button>{% endif %}
<h5>Date:{{ post.date|date:'M d Y' }}</h5>

<h6>Categories:
    {% for category in post.categories.all %}
        <button> <a href="{{post.id}}/category/{{category.id}}/subscribe"> Subscribe to a category: "{{ category.name }}"</a> </button>
    {% endfor %}
</h6>

{{ post.text|censor }}<br>
{% if is_comments %}
<h5>Comments:</h5>

{% for comment in comments %}
    <h6>User:{{ comment.user_id }} {{ comment.comment_raiting}}<br>
    {{ comment.text }}<br></h6>


{% endfor %}
{% else %}
       <h6> No comments</h6>
{% endif %}

            <button>
                    <a href="{{ post.id }}/comment">
                        Add_comment
                    </a>
            </button>
{% endblock content %}

project/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Delete post</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Delete "{{ post.heading }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <div class="post-form">
        <h1>Create a New Post</h1>
        <hr>

        <form action="" method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.heading.id_for_label }}">Heading:</label>
                {{ form.heading }}
            </div>

            <div class="form-group">
                <label for="{{ form.text.id_for_label }}">Text:</label>
                {{ form.text }}
            </div>

            <div class="form-group">
                <label for="{{ form.categories.id_for_label }}">Categories:</label>
                {{ form.categories }}
            </div>

            <input type="submit" value="Save" class="btn btn-primary" />
        </form>
    </div>
{% endblock content %}

project/templates/posts.html
<!-- Наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_tags %}
{% load custom_filters %}

<!-- Название у нас будет products -->
{% block title %}
    Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
   <h1>All posts</h1>
    {% if is_author %}
        <button> <a href="create/"> Create Post</a> </button>
        <button> <a href="news/create"> Post a news</a> </button>
    {% endif %}
   <h3>{{ time_now|date:'M d Y' }}</h3>
    <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Search" />
    </form>

    <hr>

    {% if posts %}
        <table>
            <tr>
                <td>Author</td>
                <td>Rating</td>
                <td>Heading</td>
                <td>Summary</td>
                <td>Category</td>
                <td>Type</td>
                <td>Date</td>
            </tr>

            {% for post in posts %}
                <tr>
                    <td><a href="{{post.id}}" style="text-decoration: none; color: #000;">{{ post.author.user_id.username }}</a></td>
                    <td><a href="{{post.id}}" style="text-decoration: none; color: #000;">{{ post.raiting }}</a></td>
                    <td><a href="{{post.id}}" style="text-decoration: none; color: #000;">{{ post.heading|truncatewords:3|censor}}</a></td>
                    <td><a href="{{post.id}}" style="text-decoration: none; color: #000;">{{ post.text|truncatewords:20|censor }}</a></td>
                    <td>
                        {% for category in post.categories.all %}
                            <a href="{{post.id}}" style="text-decoration: none; color: #000;">{{ category.name }}</a>
                        {% endfor %}
                    </td>
                    <td><a href="{{post.id}}" style="text-decoration: none; color: #000;">{{ post.get_state_display}}</a></td>
                    <td><a href="{{post.id}}" style="text-decoration: none; color: #000;">{{ post.date|date:'M d Y' }}</a></td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>No posts</h2>
    {% endif %}

    {# Добавляем пагинацию на страницу #}

    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
{% endblock content %}